name: build and push health-check-backend docker image to GHCR

on:
  workflow_dispatch: # Manually triggered

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: health-check-backend
        run: |
          docker build -t ghcr.io/sharonk77/devops-project:latest -t ghcr.io/sharonk77/devops-project:${{ github.sha }} .

      - name: Push latest and SHA Docker image to GitHub Packages
        run: |
          docker push ghcr.io/sharonk77/devops-project:latest
          docker push ghcr.io/sharonk77/devops-project:${{ github.sha }}

