name: Deploy ECS with Latest GHCR Image

on:
  workflow_dispatch: # currently only manually triggered

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name:  Terraform init
        working-directory: dummy-server-tf
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET_NAME }}" \
            -backend-config="key="confs/import-bootstrap/terraform.tfstate"" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-state-locking" \
            -backend-config="encrypt=true"
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_ghcr_token: ${{ secrets.GHCR_TOKEN }}

      - name: Apply Terraform Configuration
        working-directory: dummy-server-tf
        run: terraform apply -auto-approve

#      - name: Force ECS to Pull Latest Image
#        run: |
#          aws ecs update-service --cluster dummy-server-cluster --service dummy-service --force-new-deployment
